from src.handle_html.constants import BAND_MERCH_URL, COLLECTION_BASE_URL, LOCAL_HTML_PATH
from src.handle_html.get_web_html_data import GetHTML
from src.handle_html.read_local_html_data import HandleLocalHTML
from src.handle_html.manage_local_html_data import check_for_local_data, remove_local_data, prompt_for_new_data
