from src.handle_http_data.constants import BAND_MERCH_URL, COLLECTION_BASE_URL, LOCAL_HTTP_PATH
from src.handle_http_data.get_web_http_data import GetHTTP
from src.handle_http_data.read_local_http_data import HandleLocalHTTP
from src.handle_http_data.manage_local_http_data import check_for_local_data, remove_local_data, prompt_for_new_data
